import { useState } from "react";
import { BrainCircuit, CheckCircle2, ArrowRight } from "lucide-react";

interface AiWorkspaceProps {
  hasCompletedQuestionnaire: boolean;
  onCompleteQuestionnaire: (data: any) => void;
  teamProgress: any[];
}

export function AiWorkspace({ hasCompletedQuestionnaire, onCompleteQuestionnaire, teamProgress }: AiWorkspaceProps) {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState({
    strengths: "",
    learningPreferences: "",
    availability: "",
    studyGoal: ""
  });

  if (!hasCompletedQuestionnaire) {
    return (
      <div className="flex flex-col h-full bg-[#f8f9fe] px-5 py-6 pb-32 overflow-y-auto">
        <div className="mb-8 rounded-[32px] bg-[#6366f1] p-8 text-white shadow-[0_8px_30px_rgb(99,102,241,0.2)] relative overflow-hidden">
          {/* Decorative element */}
          <div className="absolute top-[-20%] right-[-10%] w-64 h-64 rounded-full bg-white/10 blur-3xl pointer-events-none" />
          
          <div className="mb-6 flex items-center gap-4 relative z-10">
            <div className="grid h-14 w-14 shrink-0 place-items-center rounded-[20px] bg-white/20 backdrop-blur-md">
              <span className="text-2xl">👋</span>
            </div>
            <div>
              <h2 className="text-[22px] font-bold tracking-tight">Welcome to Study Together!</h2>
            </div>
          </div>
          <p className="text-[16px] font-medium leading-relaxed text-white/90 relative z-10">
            Let's understand your strengths so I can create the best study plan for the team.
          </p>
          <button 
            onClick={() => setStep(1)}
            className="mt-8 w-full rounded-[20px] bg-white px-5 py-4 text-[16px] font-bold text-[#6366f1] shadow-sm hover:opacity-90 active:scale-95 transition-all relative z-10"
          >
            Let's Get Started
          </button>
        </div>

        <div className="flex flex-col gap-4">
          {[
            { id: 1, title: "1. Your Strengths", desc: "Which topics are you strong in?" },
            { id: 2, title: "2. Learning Preferences", desc: "How do you learn best?" },
            { id: 3, title: "3. Availability", desc: "How much time can you study daily?" },
            { id: 4, title: "4. Study Goal", desc: "What do you want to achieve?" }
          ].map((item) => (
            <div key={item.id} className="flex items-center justify-between rounded-[24px] bg-white border border-gray-100 p-5 shadow-[0_4px_20px_rgb(0,0,0,0.02)]">
              <div>
                <h3 className="text-[16px] font-bold text-gray-900 tracking-tight">{item.title}</h3>
                <p className="text-[14px] font-medium text-gray-500 mt-1">{item.desc}</p>
              </div>
              <CheckCircle2 className={`h-7 w-7 ${step > item.id ? "text-[#10b981]" : "text-gray-200"}`} />
            </div>
          ))}
        </div>

        {step > 0 && (
          <div className="mt-10">
             <button 
                onClick={() => onCompleteQuestionnaire(answers)}
                className="w-full flex items-center justify-center gap-2 rounded-[20px] bg-[#6366f1] px-5 py-4 text-[16px] font-bold text-white shadow-[0_4px_12px_rgb(99,102,241,0.3)] hover:opacity-90 active:scale-95 transition-all"
              >
                Continue to AI Study Plan
                <ArrowRight className="h-5 w-5" />
              </button>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-[#f8f9fe] px-5 py-6 pb-32 overflow-y-auto">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-[24px] font-bold text-gray-900 tracking-tight">Team Study Plan</h2>
          <p className="text-[15px] text-gray-500 mt-1 font-medium">Generated by Study Together AI</p>
        </div>
        <div className="grid h-14 w-14 shrink-0 place-items-center rounded-[20px] bg-[#6366f1]/10 text-[#6366f1]">
          <BrainCircuit className="h-7 w-7 stroke-[2]" />
        </div>
      </div>

      <div className="flex flex-col gap-5">
        {[
          { title: "Binary Trees", assignedTo: "Hari", status: "In Progress", progress: 60 },
          { title: "Graphs & DFS", assignedTo: "Akash", status: "Pending", progress: 0 },
          { title: "Sorting Algorithms", assignedTo: "Sanjai", status: "Pending", progress: 0 },
        ].map((topic, i) => (
          <div key={i} className="rounded-[28px] border border-gray-100 bg-white p-6 shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
            <div className="flex items-start justify-between mb-6">
              <div>
                <span className="inline-block rounded-lg bg-[#6366f1]/10 px-2.5 py-1 text-[12px] font-bold text-[#6366f1] mb-3">
                  Topic {i + 1}
                </span>
                <h3 className="text-[18px] font-bold text-gray-900 tracking-tight">{topic.title}</h3>
                <p className="text-[14px] font-medium text-gray-500 mt-1.5">
                  Assigned to <span className="font-bold text-gray-900">{topic.assignedTo}</span>
                </p>
              </div>
              <div className="flex flex-col items-end">
                <span className={`text-[13px] font-bold ${topic.progress > 0 ? "text-[#6366f1]" : "text-gray-400"}`}>
                  {topic.status}
                </span>
              </div>
            </div>
            
            <div className="mt-2">
              <button className="w-full rounded-[16px] bg-[#f8f9fa] px-5 py-3.5 text-[15px] font-bold text-gray-900 hover:bg-gray-100 transition-colors">
                Start Learning
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
